#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Disable autocorrection
unsetopt correct

# Aliases
alias ip='ip -c'
alias rg='rg --smart-case --hidden --no-ignore --max-columns=150 --max-columns-preview --no-config'
